# Update python dependencies daily

version: 2
updates:

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/3.8"
    schedule:
      interval: "daily"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: ":arrow_up:"
      include: "scope"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/3.9"
    schedule:
      interval: "daily"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: ":arrow_up:"
      include: "scope"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/3.10"
    schedule:
      interval: "daily"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: ":arrow_up:"
      include: "scope"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/3.11"
    schedule:
      interval: "daily"
    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: ":arrow_up:"
      include: "scope"
