[tool.poetry]
name = "vanilla-installer"
version = "1.0.0-dev1"
description = "An installer for Fabulously Optimized for the vanilla launcher."
authors = ["Fabulously Optimized "]
license = "MIT License"
readme = "README.md"
packages = [{include = "vanilla_installer"}]

[tool.poetry.dependencies]
python = ">=3.8,<=3.12"
requests = "^2.28.1"
tomli = "^2.0.1"
darkdetect = "^0.7.1"
minecraft-launcher-lib = "^5.2"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
