[tool.poetry]
name = "vanilla-installer"
version = "v1.0.0-dev8"
description = "An installer of Fabulously Optimized for the vanilla launcher."
authors = [
    "osfanbuff63 <osfanbuff63@osfanbuff63.tech>",
    "nsde <mail@onlix.me>"
]
documentation = "https://fabulously-optimized.github.io/vanilla-installer"
homepage = "https://fabulously-optimized.github.io/vanilla-installer"
repository = "https://github.com/Fabulously-Optimized/vanilla-installer"
license = "MIT"
readme = "README.md"
packages = [{include = "vanilla_installer"}]
include = [
    "./vanilla_installer/assets/**"
]

[tool.poetry.dependencies]
python = ">=3.8,<=3.11"
requests = "^2.28.1"
tomli = "^2.0.1"
darkdetect = "^0.7.1"
minecraft-launcher-lib = "^5.2"
click = "^8.1.3"
pyside6 = {version = "^6.4.0.1", optional = true}

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.4"
black = "^22.10.0"
cx-Freeze = "^6.13.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.1"
mkdocs-material = "^8.5.7"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}


[tool.poetry.group.ci.dependencies]
flake8 = "^5.0.4"

[tool.poetry.scripts]
vanilla-installer = {callable = "vanilla_installer:cli.vanilla_installer"}
vanilla-installer-gui = {callable = "vanilla_installer:gui.run", extras = ["gui"]}

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Fabulously-Optimized/vanilla-installer/issues"

[tool.poetry.extras]
gui = ["pyside6"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
