name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Fabulously-Optimized/vanilla-installer/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: requested-feature
    attributes:
      label: Potential Enhancement
      description: What's the feature you want to see added?
      placeholder: I want...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: How it could be implemented
      description: Give as much detail as possible how this could be implemented
      placeholder: Use [this](https://pypi.org/project/this)
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else?
      description: If there's anything else that might be relevant, put it here.
    validations:
      required: false
